### ISSUE TITLE
map page absent

### ISSUE THREAD

**Issue by alexdruk** [GitTerraGame/GitTerra#11]
- in some cases git hangs  -  #12 
- usecase1: Private repo.Ask for username and password #13
- correct repo name, but empty repository #14
- deep link to map that was never generated #15
- valid URL, but not a repository (typos and etc) #13

**Comment by alexdruk** [comment]
#12 and  #13  implemented

**Comment by sergeychernyshev** [comment]
Closing this summary ticket as useless
