### ISSUE TITLE
hanging git process

### ISSUE THREAD

**Issue by alexdruk** [GitTerraGame/GitTerra#12]
Implement rolling timeout with simple-git and redirect user to special error page with message "We are having troubles building your city. Please try again later and/or report the problem<link to bug issue> "

**Comment by alexdruk** [comment]
implemented by adding timeout in simple-git

**Comment by alexdruk** [comment]
not implemented yet: redirect user to special error page with message "We are having troubles building your city. Please try again later and/or report the problem "

**Comment by AlexanderChernyshev** [comment]
Added an animated SVG and background image for this page into the backgrounds and menus folder.
