### ISSUE TITLE
empty repo

### ISSUE THREAD

**Issue by alexdruk** [GitTerraGame/GitTerra#14]
if repo is empty scc returns empty json. We can redirect to error page with  message like ~"start building your project"

**Comment by alexdruk** [comment]
this issue waiting for Alex to design a special page for case with empty json

**Comment by sergeychernyshev** [comment]
Well, this is a moot point now that you have to have at least a workflow file to run the game, plus we don't do that, it's built using CI/CD.

This is an empty repo game example with just one tile: https://github.com/GitTerraGame/empty-repo
