### ISSUE TITLE
404 response in the folder "map" (deep link?)

### ISSUE THREAD

**Issue by alexdruk** [GitTerraGame/GitTerra#15]
A special page with prepopulated url,  message "This is not city you are looking for! Would you like to build it?" (Copy 404 from github)

**Comment by alexdruk** [comment]
Alex please design a 404 page

**Comment by sergeychernyshev** [comment]
You can mention him in the issue for him to get notified, e.g.:

"Hey, @AlexanderChernyshev, please design a 404 page"

**Comment by sergeychernyshev** [comment]
Here's a React example for making a mouse-driven parallax:
https://codesandbox.io/embed/r5x34869vq

**Comment by alexdruk** [comment]
implemented

**Comment by sergeychernyshev** [comment]
This is not complete as this page does not invite user to try and generate it.

**Comment by sergeychernyshev** [comment]
We got the page. Not sure what it will be now that it is all in CI, but we can keep the error page for sure.

**Comment by sergeychernyshev** [comment]
https://gitterra.com/404
