### ISSUE TITLE
Node API server has permissions issues

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#21]
JS API server has permissions issues when executed.

It looks like simple-git tries to change the git configuration in the current working directory (which is not where it checks out the files) which causes it to fail due to permissions issues (it can't write into the root of our repo).

We need to convince it not to do that, e.g. by setting a base URL to the place it checks out the code or something like that.

**Comment by sergeychernyshev** [comment]
I had to roll back API server to use a shell script until this is fixed.

**Comment by alexdruk** [comment]
If you set up base directory in simple-git, it clone repo to basedir/reponame like tmpDir/GitTerra. this not a big problem - we just need to append reponame to tmpDir. Bur will it solve the api permissions problem?

**Comment by alexdruk** [comment]
seems to fixed with 7775d15 commit
