### ISSUE TITLE
Create feedback mechanism

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#3]
Make it easy to submit feedback for the project.

**Comment by alexdruk** [comment]
created a link to https://github.com/GitTerraGame/GitTerra/issues

**Comment by sergeychernyshev** [comment]
Let's add "how can we make this game better" issue template and use it. Also let's add "feedback" label on these.
Also, let's move the question with the link right under the logo.

Query string params description:
https://docs.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters

**Comment by alexdruk** [comment]
1. Updated link from html
2. Created config.yml
3. Created 3 templates:
  - name: Regular issue
    url: https://github.com/GitTerraGame/GitTerra/issues/new?template=regular_template.md&labels=enhancement
  - name: Bug Report
    url: https://github.com/GitTerraGame/GitTerra/issues/new?template=bug_template.md&labels=bug
  - name: YourFeedback
    url: https://github.com/GitTerraGame/GitTerra/issues/new?template=feedback.md&labels=feedback

**Comment by alexdruk** [comment]
I believe this issues should be closed
