### ISSUE TITLE
Minimum size is too aggressive

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#36]
Small repositories with little code are considered empty and map is not generated for them.

Example repo:
https://github.com/sergeychernyshev/queue-cli

It has some code, but [this check](https://github.com/GitTerraGame/GitTerra/blob/main/src/generateMap.js#L38-L40) returns false and no map is generated for it.

We should probably check if raw values are non-zero instead and generate a map with the minimum amount of tiles.

**Comment by alexdruk** [comment]
Still an issue of #14

**Comment by sergeychernyshev** [comment]
This doesn't seem to be a problem anymore.
