### ISSUE TITLE
Generate map per repository

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#4]
Instead of generating single `map.html`, generate a unique page per repository URL.

URL examples:
https://gitterra.com/github.com/StartupAPI/users/index.html
https://gitterra.com/gitlab.com/Scorchsoft/opl-data/index.html

Filename pattern:
`/repos/:host/:owner/:repo/index.html`

**Comment by alexdruk** [comment]
I have created unique index.html in repository, but to show images have to create relative path for them in map.js - '../../../../' 
We have to configure root path for local and production

**Comment by sergeychernyshev** [comment]
As we discussed, using relative paths like that are probably OK for now.

**Comment by alexdruk** [comment]
So, I CLOSE THIS ISSUE
