### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#5]
Create a page with an input field to ask user to enter the repo URL.

Design from Alexander.

Form needs to use AJAX calls to:
1.  trigger the API for map generation (`/api/generateMap`)
2. show "the city is being built" while generation is happening and check for progress using another API endpoint (`/api/getMapStatus`)
3. and once complete, redirect user to the repo page.

**Comment by alexdruk** [comment]
it seems I did it, but it will require revision after issue #6  will be done

**Comment by sergeychernyshev** [comment]
No, it is far from done, starting with the styling of the element - we might just abandon triangular shapes on it and just go with a regular box.

But also, there is no UI for "the city is being built" state of the page and no logic for redirection to the final page once it is built.

**Comment by alexdruk** [comment]
Sorry, latest version of index.html somehow was not submitted. This can cause confusion

**Comment by sergeychernyshev** [comment]
I believe there are bugs in this code right now - basically if API server does not respond with success on the first status call, UI never updates as [`setInterval()` call](https://github.com/GitTerraGame/GitTerra/blob/main/src/index.html#L133-L135) just checks the status, but doesn't do anything with it. BTW, something also needs to remove setInterval execution as it will be happening forever unless removed, alternatively, it can use `setTimeout()` and then call it every time we don't get a successful response.

**Comment by alexdruk** [comment]
seems to be OK

**Comment by alexdruk** [comment]
seems to be OK
