### ISSUE TITLE
Generation API server

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#6]
Create API server using node and Express with two endpoints:

- POST `/api/generateMap` to start map generation
  - accepts `{"repo": "https://github.com/GitTerraGame/GitTerra"}` object as `application/json` POST body
- POST `/api/mapStatus` for checking generation progress
  - accepts `{"repo": "https://github.com/GitTerraGame/GitTerra"}` object as `application/json` POST body
  - return `{"complete": false}` while in progress and `{"complete": true, "mapPageURL": "/github.com/StartupAPI/users/index.html"}` when finished

Both endpoints should handle errors.

**Comment by alexdruk** [comment]
at least MapStatus should handle RATE LIMIT

**Comment by sergeychernyshev** [comment]
Why are you concerned with the rate limit here?

**Comment by alexdruk** [comment]
some work left to be done See #11
