### ISSUE TITLE
Deterministic map

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#63]
## Description

Currently the city is generated randomly based on the total number of lines of code.

This does not keep the consistency between small changes, every time the map is built tiles are all different from previous time no matter how small the change was.

Let's figure out how we can make a map stay more or less consistent from build to build and growing as repository grows.

## Steps

- Figure out clustering technique splitting whole city into districts (probably just one district for now with the center on the bottom)
- Assign individual files to a set of blocks in each `district` based on a total size.
  - Figure out how to make assigning files to districts consistent.
- Aggregate metrics for each `block` to determine the tile (e.g. specific number in a list of tiles in a tileset) and it's properties (e.g. primary color, based on dominant programming language, for example), make ordering of blocks consistent to keep their position intact.

**Comment by sergeychernyshev** [comment]
Deterministic map implemented, not used for coloring yet, but that can be done easily by scanning the same set of files for primary language and all that.

Otherwise, it works at the moment and is more or less deterministic.

Once we need to better group by language or by folder structure proximity, we can try updating the algorithm to use those parameters instead of just pure file size and lines of code.

**Comment by AlexanderChernyshev** [comment]
Closing it since we plan on letting players build maps instead of full auto gen.
