### ISSUE TITLE
Use programming languages for primary color

### ISSUE THREAD

**Issue by sergeychernyshev** [GitTerraGame/GitTerra#64]
## Description

Make it possible to adjust a primary color of a tile to match a programming language of the block.

No matter how we determine the primary programming language, when it is picked, corresponding color should be used.

## Steps

- Determine how to adjust tile color for each individual tile
  - option 1: create unique tile files by replacing specific color with a target color using some stupid process like grep. The benefit is that files don't need to be specially prepared, just need to use a unique colors for the color that needs to be replaced
  - option 2: annotate all elements that need to be colorized using a class in SVG and create custom classes that style fill color for specific DOM nodes. Requires to use SVGs inline in HTML rather than as external file references.
- Annotate all tile sets/tiles with which specific components need to be re-colored
- Make use of language data to assign color to each individual block

## Additional requirements

Figure out the mapping for most programming languages supported by SCC. Most likely use brand primary colors, maybe also record a secondary color as well.

In play-testing interviews players suggested using GitHub colors, it also seems that GitLab uses some language color maps as well.

**Comment by AlexanderChernyshev** [comment]
Done in version 1.1
